# Generated by Django 5.2.13 on 2026-05-29 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivebot', '0009_populate_wikipedias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edits', models.PositiveIntegerField(default=0, help_text='Total number of edits')),
                ('urls_archived', models.PositiveIntegerField(default=0, help_text='Total number of URLs archived')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wikipedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archivebot.wikipedia')),
            ],
            options={
                'ordering': ('-edits', '-urls_archived'),
            },
        ),
    ]
