# Generated by Django 5.2.13 on 2026-05-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='articles',
            field=models.PositiveIntegerField(default=0, help_text='Total number of articles edited'),
        ),
    ]
