# Generated by Django 5.2.13 on 2026-06-10 20:18

import django.db.models.deletion
from django.db import migrations, models


def leave_unique_statistics(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Statistics = apps.get_model("stats", "Statistics")
    Timestamp = apps.get_model("stats", "Timestamp")
    ts = Timestamp.objects.first()
    Statistics.objects.using(db_alias).exclude(timestamp=ts).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0009_populate_wikipedias'),
        ('stats', '0002_statistics_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True)),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ('timestamp', '-edits'), 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterField(
            model_name='statistics',
            name='wikipedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivebot.wikipedia'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.timestamp'),
        ),
        migrations.AddConstraint(
            model_name='statistics',
            constraint=models.UniqueConstraint(fields=('wikipedia', 'timestamp'), name='unique_wikipedia_timestamp'),
        ),
        migrations.RunPython(
            reverse_code=leave_unique_statistics,
            code=migrations.RunPython.noop,
        ),
    ]
