# Generated by Django 5.2.3 on 2025-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('article_title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotRunStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('articles_scanned', models.IntegerField()),
                ('urls_checked', models.IntegerField()),
                ('urls_archived', models.IntegerField()),
                ('edits_made', models.IntegerField()),
            ],
        ),
    ]
