# Generated by Django 4.2.24 on 2025-10-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0002_archivedcitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveLog',
        ),
    ]
