# Generated by Django 4.2.25 on 2025-11-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0004_remove_archivedcitation_arquivodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('edit_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(blank=True, choices=[('running', 'check running'), ('archived', 'successful archive'), ('failed', 'archive failed'), ('ignored_permalink', 'Permalink ignored'), ('ignored_archived', 'URL already archived')], default='running', max_length=32)),
                ('archive_url', models.URLField(blank=True, null=True)),
                ('is_url_dead', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='archivebot.articlecheck')),
            ],
        ),
        migrations.CreateModel(
            name='Wikipedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="'pt', 'test', etc", max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='ArchivedCitation',
        ),
        migrations.DeleteModel(
            name='BotRunStats',
        ),
        migrations.AddField(
            model_name='articlecheck',
            name='wikipedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivebot.wikipedia'),
        ),
    ]
