# Generated by Django 4.2.26 on 2025-12-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0006_articlecheck_diff_new_id_articlecheck_diff_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlcheck',
            name='is_url_dead',
        ),
    ]
