# Generated by Django 5.2.11 on 2026-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0007_remove_urlcheck_is_url_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipedia',
            name='bot_edit',
            field=models.BooleanField(default=True, help_text='If to mark edits as a bot edit'),
        ),
    ]
