# Generated by Django 5.2.11 on 2026-03-19 17:07

from django.db import migrations

def populate_wikipedias(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Wikipedia = apps.get_model("archivebot", "Wikipedia")
    pt, _ = Wikipedia.objects.using(db_alias).get_or_create(code="pt")
    pt.bot_edit = True
    pt.save()
    test, _ = Wikipedia.objects.using(db_alias).get_or_create(code="test")
    test.bot_edit = False
    test.save()

class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0008_wikipedia_bot_edit'),
    ]

    operations = [
        migrations.RunPython(
            code=populate_wikipedias,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
