# Generated by Django 5.2.14 on 2026-08-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0009_populate_wikipedias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcheck',
            name='status',
            field=models.CharField(blank=True, choices=[('running', 'check running'), ('archived', 'successful archive'), ('failed', 'archive failed'), ('ignored_permalink', 'Permalink ignored'), ('ignored_archived', 'URL already archived'), ('ignored_wikimedia', 'Wikimedia URL ignored')], default='running', max_length=32),
        ),
    ]
