# Generated by Django 5.2.3 on 2025-07-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('original_template', models.TextField()),
                ('updated_template', models.TextField()),
                ('url', models.URLField()),
                ('arquivourl', models.URLField(blank=True, null=True)),
                ('arquivodata', models.DateField(blank=True, null=True)),
                ('urlmorta', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
