# Generated by Django 4.2.24 on 2025-10-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0003_delete_archivelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcitation',
            name='arquivodata',
        ),
    ]
