# Generated by Django 4.2.25 on 2025-11-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebot', '0005_articlecheck_urlcheck_wikipedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecheck',
            name='diff_new_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecheck',
            name='diff_old_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
